### PR TITLE
Upgrade jekyll

### PR DESCRIPTION
**Pull request by chamook**
Got fed up of my other PR being open 🙃

Hopefully this solves some of the build issues by upgrading to a newer version of Jekyll - it works locally, but I have no idea if netlify needs anything special 🤷‍♂️

### CODE REVIEW

**Comment by chamook** [comment]
Well, I suppose expecting it to work was a bit much 🤷‍♂️

**Comment by hybridcattt** [comment]
I don't believe I've seen this PR before now 🙈🙈🙈

**Comment by chamook** [comment]
😅 I don't know if it's out of date now, but was there anything useful in the deployment log for fixing it?

**Comment by chamook** [comment]
Oh I thought this was superseded by your changes?

**Pull request closed without merging**
